### ISSUE TITLE
Can't not using on nhentai

### ISSUE THREAD

**Issue by hentaikishi** [hanFengSan/eHunter#189]
[step]
1.Install Tampermonkey / Tampermonkey Beta on Chrome / Brave 
2.Install ehunter on Tampermonkey
3.Enable ehunter on Tampermonkey
4.Going to nhentai and click a book with entery the book 

[actual results]
Will always show Reading animation
Sometime will show textcontent error

[expected outcome]
After the Reading will show the books

[reproduction rate]
fail rate: 100%

[Other]
This plug can using on exhentai and ehentai
1.after clear cookies and re-launch Chrome / Brave still like pre-action
2.Reinstall ehunter is the same action

[software information]
ehunter ver: 2.7.3
Tampermonkey Beta version:5.2.6195
Tampermonkey veriosn:5.1.1
Brave version: 4.65.130 with Chromium 124.0.6367.159
Chrome version:124.0.6367.201
![image](https://github.com/hanFengSan/eHunter/assets/46550898/d87c6f39-a640-4d13-a6e4-655e73c93073)

**Comment by hanFengSan** [comment]
thank you, I will check it.

onmyojiarena ***@***.***> 于 2024年5月11日周六 00:55写道：

**Comment by LukeAitch** [comment]
I'm currently experiencing the same issue.

**Comment by hyl59** [comment]
same

**Comment by Yikage** [comment]
same issue

**Comment by hyl59** [comment]
solved

**Comment by hentaikishi** [comment]
Hi @hyl59  and @hanFengSan,
this issue is resolved, maybe nhentai have some change in less days makes this pl

**Comment by LukeAitch** [comment]
> Hi @hanFengSan, this issue is happened again, However, I have discovered a pattern. Before the continuous reading screen appears, there will be a cloudflare verification.

Yeah me too, I'm experiencing this issue again and on the same conditions.

**Comment by hanFengSan** [comment]
Is the issue still occurring? You can try v3.0.0：openuserjs.org/scripts/alexchen/eHunter

**Comment by onmyojiarena** [comment]
Right now on version 2.8.0 it works fine, havn't tried versions yet
